import setuptools

require = ['asyncio',
           'atomicwrites',
           'attrs',
           'certifi',
           'chardet',
           'colorama',
           'decorator',
           'future',
           'get',
           'idna',
           'iso-639',
           'iso3166',
           'isodate',
           'lxml',
           'more-itertools',
           'pluggy',
           'post',
           'psutil',
           'public',
           'py',
           'pycryptodome',
           'PySocks',
           'pytest',
           'query-string',
           'requests',
           'six',
           'streamlink',
           'urllib3',
           'websocket-client',
           'youtube-dl',
           ]

setuptools.setup(
    name='Auto-Record-Matsuri',
    version='0.8',
    description='A tiny program can automatically fetch Youtube LIVE and Mirrativ LIVE.',
    author='FZxiao',
    author_email='fzxiao@outlook.com',
    license='MIT',
    url='https://github.com/fzxiao233/Auto_Record_Matsuri',
    download_url='https://github.com/fzxiao233/Auto_Record_Matsuri/archive/0.8.tar.gz',
    packages=setuptools.find_packages(),
    install_requires=require,
    classifiers=["Environment :: Console",
                 "Operating System :: Microsoft :: Windows",
                 "Operating System :: Linux",
                 "Programming Language :: Python :: 3.7",
                 "Topic :: Internet :: WWW/HTTP",
                 "Topic :: Multimedia :: Sound/Audio",
                 "Topic :: Multimedia :: Video",
                 "Topic :: Utilities"])
